from dataclasses import dataclass

from google import genai
from google.genai import types

from backend.config import Settings
from backend.schemas import DocumentRequest
from backend.utils.text_utils import terms_to_list


@dataclass
class GeneratedDocument:
    """
    Result produced by the AI document generator.
    """

    content: str
    demo_mode: bool = False


class GeminiDocumentGenerator:
    """
    Gemini-powered legal document generator.
    """

    def __init__(self, settings: Settings):
        self.settings = settings
        self.client = None

        if settings.gemini_api_key:
            self.client = genai.Client(
                api_key=settings.gemini_api_key
            )

    def generate_document(
        self,
        request: DocumentRequest,
    ) -> GeneratedDocument:
        """
        Generate a legal document using Gemini.
        """

        if self.settings.demo_mode:
            return GeneratedDocument(
                content=self._demo_document(request),
                demo_mode=True,
            )

        if self.client is None:
            raise RuntimeError(
                "GEMINI_API_KEY is not configured. "
                "Add it to your .env file or set "
                "DEMO_MODE=true for local testing."
            )

        prompt = self._build_prompt(request)

        response = self.client.models.generate_content(
            model=self.settings.gemini_model,
            contents=prompt,
            config=types.GenerateContentConfig(
                temperature=self.settings.ai_temperature,
                max_output_tokens=(
                    self.settings.ai_max_output_tokens
                ),
            ),
        )

        content = getattr(
            response,
            "text",
            None,
        )

        if not content or not content.strip():
            raise RuntimeError(
                "Gemini returned an empty document."
            )

        return GeneratedDocument(
            content=content.strip(),
            demo_mode=False,
        )

    def _build_prompt(
        self,
        request: DocumentRequest,
    ) -> str:
        """
        Construct the Gemini prompt.
        """

        terms = terms_to_list(
            request.terms
        )

        term_block = "\n".join(
            f"- {item}"
            for item in terms
        )

        prompt = f"""
You are the document drafting engine for LegalEase,
an AI-assisted legal document drafting application.

IMPORTANT RULES:

1. Produce a professional DRAFT.
2. Do not claim that the document is legally valid.
3. Do not invent names, dates, addresses, amounts,
   laws, registration numbers, or other facts.
4. If important information is missing, use:
   [MISSING INFORMATION: description]
5. Keep the document internally consistent.
6. Do not assume a jurisdiction that was not supplied.
7. Do not claim to be a lawyer.
8. Do not provide hidden reasoning or chain-of-thought.
9. Use clear professional legal language.
10. Include a Review Notice at the end.

DOCUMENT TYPE:
{request.document_type}

PARTIES:
{request.parties}

EFFECTIVE DATE:
{request.effective_date}

JURISDICTION:
{request.jurisdiction}

PURPOSE:
{request.purpose or "Not provided"}

REQUESTED TERMS:
{term_block}

ADDITIONAL INSTRUCTIONS:
{request.additional_instructions or "None"}

Create the document with this general structure when
appropriate:

1. Document title
2. Background / Recitals
3. Definitions if necessary
4. Main numbered clauses
5. Obligations and responsibilities
6. Payment terms where applicable
7. Confidentiality where applicable
8. Term and termination where applicable
9. Governing law where applicable
10. Dispute resolution where applicable
11. Signatures
12. Review Notice

Return ONLY the document draft.
"""

        return prompt.strip()

    @staticmethod
    def _demo_document(
        request: DocumentRequest,
    ) -> str:
        """
        Create a deterministic document for local testing.
        """

        terms = terms_to_list(
            request.terms
        )

        if terms:
            term_lines = "\n".join(
                f"{index}. {term}"
                for index, term in enumerate(
                    terms,
                    start=1,
                )
            )
        else:
            term_lines = (
                "No specific terms supplied."
            )

        return f"""
DEMO DRAFT - {request.document_type.upper()}

PARTIES

{request.parties}


EFFECTIVE DATE

{request.effective_date}


JURISDICTION

{request.jurisdiction}


1. PURPOSE

This demonstration draft was generated by
LegalEase from the information supplied by
the user.

It is intended to verify the application's
generation, editing, and export pipeline.


2. REQUESTED TERMS

{term_lines}


3. GENERAL PROVISIONS

The parties should review this document and
complete all missing factual, commercial, and
jurisdiction-specific provisions before using
the document for a real transaction.


4. SIGNATURES

Party 1:

Signature: ______________________________

Name: ___________________________________

Date: ___________________________________


Party 2:

Signature: ______________________________

Name: ___________________________________

Date: ___________________________________


REVIEW NOTICE

This is a demonstration draft and is not
legal advice. The completed document should
be reviewed by a qualified legal professional
for the applicable facts and jurisdiction
before use.
""".strip()